
# tasks file for roles/sonarqube
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present



- name: Install unzip package
  apt:
    name: unzip
    state: present


- name: Download SonarQube zip
  get_url:
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-8.9.1.44547.zip
    dest: /opt/sonarqube.zip

- name: Extract SonarQube
  unarchive:
    src: /opt/sonarqube.zip
    dest: /opt/
    remote_src: yes
    # creates: /opt/sonarqube-8.9.1.44547/  # Adjust this path based on the extracted SonarQube directory name

- name: Set ownership and permissions
  file:
    path: /opt/sonarqube-8.9.1.44547/  # Adjust this path based on the extracted SonarQube directory name
    owner: ubuntu
    group: ubuntu
    recurse: yes
    state: directory

- name: Configure SonarQube
  template:
    src: templates/sonarqube.service.j2
    dest: /opt/sonarqube-8.9.1.44547/conf/sonarqube.service  # Adjust this path based on the extracted SonarQube directory name

- name: Update package cache
  apt:
    update_cache: yes

- name: Create systemd service file
  template:
    src: sonarqube.service.j2
    dest: /etc/systemd/system/sonarqube.service

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start SonarQube service
  systemd:
    name: sonarqube
    state: started
    enabled: yes
